# Generated by Django 4.0 on 2022-07-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fish_species'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fish',
        ),
    ]
